### ISSUE TITLE
muiti-player issus

### ISSUE THREAD

**Issue by jdunn1019** [kingmodsnet/FS25_SuperForce#1]
No errors dont work on Dedicated Servers

**Comment by monsieurbab** [comment]
I am aware of the problem. For now I can't solve it, but as soon as I have access to the LUA code of the game I will fix the problem and publish an update.

**Comment by monsieurbab** [comment]
Fixed in [V1.0.0.1](https://github.com/kingmodsnet/FS25_SuperForce/releases/tag/V1.0.0.1)
