### ISSUE TITLE
Multiplayer Mod not working at all

### ISSUE THREAD

**Issue by imoDDomi** [kingmodsnet/FS25_SuperForce#2]
If someone hosts a game and you join as a client, the mod is not working. Only the Host can use the mod.

**Comment by monsieurbab** [comment]
I am aware of the problem. For now I can't solve it, but as soon as I have access to the LUA code of the game I will fix the problem and publish an update.

**Comment by monsieurbab** [comment]
Fixed in [V1.0.0.1](https://github.com/kingmodsnet/FS25_SuperForce/releases/tag/V1.0.0.1)
